[project]
name = "graphs"
version = "0.1.0"
description = "Langgraph template for RAG Evaluation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]