version: '3.8'
services:
  backend:
    build:
      context: ./RAG_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./RAG_backend/app:/app/app

  rag_evaluation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - .:/app