version: '3.8'
services:
  backend:
    build:
      context: ./RAG_backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./RAG_backend/app:/app/app

  frontend:
    build:
      context: ./RAG_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./RAG_frontend/src:/app/src

  rag_evaluation:
    build:
      context: ./RAG_Evaluation
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./RAG_Evaluation:/app
