
# docker-compose.yml
services:
  # MongoDB Service
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "9017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  # Mongo Express Service
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "9018:8081"
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongo # Tells this service to wait for the mongo service to be ready

# Top-level declaration for the named volume used by the mongo service
volumes:
  mongo-data:

