version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 9017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9018:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:changeme@host.docker.internal:9017/
    depends_on:
      - mongo