version: "3.8"
services:
  api:
    build: .
    container_name: myapi
    ports:
      - "8001:8001"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"