services:
  api:
    build: .
    container_name: myapi
    ports:
      - "8001:8001"
    depends_on:
      - cache_redis
    environment:
      - REDIS_HOST=cache_redis
      - REDIS_PORT=6379

  cache_redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"
