services:
  api:
    build: .
    container_name: myapi
    ports:
      - "8002:8002"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"